- name: install and start nignx
  hosts: local
  become: yes
  tasks:
  - name: install nignx
    ansible.builtin.package:
      name: nignx
      state: present
    
  - name: start nignx
    ansible.builtin.service:
      name: nignx
      state: started
      enabled: yes