- name: play 1
  hosts: local
  tasks:
  - name: play 1 and task 1
    ansible.builtin.debug:
      msg: "this is play 1 and task 1"

- name: play 2
  hosts: local
  tasks:
  - name: play 2 and task 1
    ansible.builtin.debug:
      msg: "this is play 2 and task 1"

- name: play 3
  hosts: local
  tasks:
    - name: play 3 and task 1
      ansible.builtin.debug:
        msg: "this play 3 and task 1"
