- name: variables from the files
  hosts: local
  connections: local
  vars_files:
  - vars.yml
  tasks:
  - name: print the candidate info
    ansible.builtin.debug:
      msg: " name : {{name}}, date of birth : {{ dob }}, qulafication : {{ qulafication }}, phone number : {{ number }}, hobbies : {{ hobbies }}"