- name: reading
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: what is your username : 
    private: false
  - name: password
    prompt: what is your password
    private: true
  tasks:
  - name: print the credentails
    ansible.builtin.debug:
      msg: "your username is : {{ username }}, your password is {{ password }}"